config/routes.rb
Rails.application.routes.draw do

  get 'admin' => 'admin#index'
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  scope '(:locale)' do
    resources :users
    resources :orders
    resources :line_items
    resources :carts
    resources :products do
      get :who_bought, :on => :member
    end
    root :to => 'store#index', :as => 'store'
  end

  get 'store/index'

  resources :products

  

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pragprog Book Online Store</title>
  <%#= stylesheet_link_tag "scaffold" %>
  <%= stylesheet_link_tag "depot", :media => "all" %>
  <%#= javascript_include_tag :defaults %>
  <%= csrf_meta_tags %>
</head>
<body id="store">
    <div id="banner">
      <%= form_tag store_path, method: :get, :class => 'locale' do %>
         <%= select_tag 'set_locale', options_for_select(LANGUAGES, I18n.locale.to_s), :onchange => 'this.form.submit()' %>
         <%= submit_tag '提交'%>
         <%= javascript_tag "$$('.locale input').each(Element.hide)" %>
      <% end %>
    	<%= image_tag("logo.jpg", :size => "60x50") %>
    	<%= @page_title || t('.title') %>
    </div>
    
    <div id="columns">
    	<div id="side">
        <div id="cart">
        <% if @cart %>
           <%= hidden_div_if(@cart.line_items.empty?, :id => "cart") do %>
           <%= render @cart %>
           <% end %>
        <% end %>
        </div>
    		<a href="http://www...."><%= t('.home') %></a><br/>
    		<a href="http://www..../faq"><%= t('.questions') %></a><br/>
    		<a href="http://www..../news"><%= t('.news') %></a><br/>
    		<a href="http://www..../contact"><%= t('.contact') %></a><br/>
    		<hr>
    	<div id="time">
    		<%= @time %>
    	</div>

      <% if session[:user_id] %>
        <br/>
        <%= link_to '订单', orders_path %><br/>
        <%= link_to '产品', products_path %><br/>
        <%= link_to '用户', users_path %><br/>
        <br/>
        <%= button_to '注销', logout_path, :method => :delete %>
        <% end %>
    	</div>
    
    	<div id="main">
    		<%= yield %>
    	</div>
    </div>

</body>
</html>